### ISSUE TITLE
Do not query all customers when there are no customer parameters in lookup endpoint

### ISSUE THREAD

**Issue by lasong** [OpusCapita/routing#13]
To reproduce, make this call below:

![image](https://user-images.githubusercontent.com/1188617/42457101-d15eac1a-8396-11e8-93d2-6fe80ae5f55a.png)

**Comment by StefanDywersant** [comment]
The problem was that api did not throw error on request without any receiver identifiers. It queried supplier/customer services for all tenants and picked first one.

Now api throws error when there are no suitable receiver identifiers.
