### ISSUE TITLE
Fix Finnish Labels

### ISSUE THREAD

**Issue by nczeranka** [OpusCapita/routing#20]
part of OpusCapita/businessnetwork/issues/212

---

see page 15 of of https://github.com/OpusCapita/businessnetwork/files/2281049/Translations.FIN.pptx

**Comment by toreskogp** [comment]
See also page 3, since that is a component loaded from routing

**Comment by kwierchris** [comment]
Ok, talked to Arne. We're not doing it like this. We have a translation matrix extraction system for that.
